version: '3.7'

services:
  postgres:
    image: postgres:12.1
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    build: .
    ports:
      - 9292:9292
    volumes:
      - .:/app
    environment:
      - LANG=C.UTF-8
      - POSTGRES_HOST=postgres
    command: bundle exec rackup config.ru -o 0.0.0.0

volumes:
  postgres:
