version: '3.7'

services:
  postgres:
    image: postgres:12.1
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    depends_on:
      - postgres
    build: .
    ports:
      - 9292:9292
    volumes:
      - .:/app
    environment:
      - LANG=C.UTF-8

volumes:
  postgres:
