version: "3.7"

services:
  postgres:
    image: postgres:12.1
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - target: 9292
        published: 9292
        protocol: tcp
        mode: host
    volumes:
      - .:/app
    environment:
      - LANG=C.UTF-8
      - POSTGRES_HOST=postgres
    command: ["bin/rackup", "-o", "0.0.0.0"]
    depends_on:
      - postgres

volumes:
  postgresql-data:
